### ISSUE TITLE
gambia has typo gabmia with several copy-paste repeats

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [mikelodder7/celes#10]
https://github.com/mikelodder7/celes/blob/main/src/lib.rs#L871
https://github.com/mikelodder7/celes/blob/main/src/lib.rs#L2548
https://github.com/mikelodder7/celes/blob/main/src/lib.rs#L3253

**Comment by yasamoka** [comment]
I think it's better to issue a PR for these changes.

**Comment by mikelodder7** [comment]
About time I fixed this. Resolved in new release `2.5.0`
