### ISSUE TITLE
from country name: handle timorleste also by english name: east timor

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [mikelodder7/celes#12]
https://en.wikipedia.org/wiki/East_Timor
https://github.com/mikelodder7/celes/blob/main/src/lib.rs#L2851

**Comment by yasamoka** [comment]
I think it's better to issue a PR for these changes.

**Comment by mikelodder7** [comment]
About time I fixed this. Resolved in new release `2.5.0`
