### ISSUE TITLE
A way to enumerate all countries

### ISSUE THREAD

**Issue by segler-alex** [mikelodder7/celes#2]
Hi, thank you for your work!
i would really need a way to enumerate all countries into a list.
could you add that feature?
i really like the features you already have and i use them for https://github.com/segler-alex/radiobrowser-api-rust
but without also having a list of all countries i cannot be fully happy :)

**Comment by mikelodder7** [comment]
Glad to hear you like it. 

There's already a function for this:

`Country::get_countries()`
